intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

lib{wine}: {hxx ixx txx cxx}{** -version} \
           {hxx            }{    version} \
           $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBWINE_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBWINE_SHARED_BUILD

# Export options.
#
lib{wine}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{wine}: cxx.export.poptions += -DLIBWINE_STATIC
libs{wine}: cxx.export.poptions += -DLIBWINE_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{wine}: bin.lib.version = "-$version.project_id"
else
  lib{wine}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libwine/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libwine/
  install.subdirs = true
}
